# Generated by Django 3.2.7 on 2021-10-27 09:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ISCO',
            fields=[
                ('Code', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Group', models.TextField()),
                ('Name', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Career', models.TextField()),
                ('HardSkill', models.TextField()),
                ('SoftSkill', models.TextField()),
                ('Personality', models.TextField()),
            ],
        ),
    ]
