# Generated by Django 3.2.7 on 2021-10-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isco',
            old_name='Code',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='jobanalysis',
            old_name='id',
            new_name='_id',
        ),
    ]
